[package]
authors.workspace      = true
description            = "A binary for running stress tests against the Miden node"
edition.workspace      = true
exclude.workspace      = true
homepage.workspace     = true
keywords               = ["miden", "stress-test"]
license.workspace      = true
name                   = "miden-node-stress-test"
readme.workspace       = true
repository.workspace   = true
rust-version.workspace = true
version.workspace      = true

[lints]
workspace = true

[dependencies]
anyhow                    = { workspace = true }
clap                      = { version = "4.5", features = ["derive", "string"] }
futures                   = { version = "0.3" }
miden-air                 = { workspace = true }
miden-block-prover        = { version = "0.8", features = ["testing"] }
miden-lib                 = { workspace = true }
miden-node-block-producer = { workspace = true }
miden-node-proto          = { workspace = true }
miden-node-store          = { workspace = true }
miden-node-utils          = { workspace = true }
miden-objects             = { workspace = true, features = ["testing"] }
rand                      = { version = "0.9" }
rayon                     = { version = "1.5" }
tokio                     = { workspace = true, features = ["macros", "net", "rt-multi-thread", "sync", "time"] }
tonic                     = { workspace = true }
winterfell                = { version = "0.12" }
