[package]
authors.workspace      = true
description            = "Miden node token faucet"
edition.workspace      = true
homepage.workspace     = true
keywords               = ["faucet", "miden", "node"]
license.workspace      = true
name                   = "miden-faucet"
readme                 = "README.md"
repository.workspace   = true
rust-version.workspace = true
version                = "0.8.1"

[lints]
workspace = true

[dependencies]
anyhow           = { workspace = true }
axum             = { version = "0.8", features = ["tokio"] }
clap             = { version = "4.5", features = ["derive", "string"] }
http             = { workspace = true }
http-body-util   = "0.1"
miden-lib        = { workspace = true }
miden-node-proto = { workspace = true }
miden-node-utils = { workspace = true }
miden-objects    = { workspace = true }
miden-tx         = { workspace = true, features = ["concurrent"] }
mime             = "0.3"
rand             = { workspace = true }
rand_chacha      = "0.9"
serde            = { version = "1.0", features = ["derive"] }
static-files     = "0.2"
thiserror        = { workspace = true }
tokio            = { workspace = true, features = ["fs"] }
toml             = { version = "0.8" }
tonic            = { workspace = true }
tower            = { workspace = true }
tower-http       = { workspace = true, features = ["cors", "set-header", "trace"] }
tracing          = { workspace = true }
url              = { workspace = true }

[build-dependencies]
# Required to inject build metadata.
miden-node-utils = { workspace = true, features = ["vergen"] }
static-files     = "0.2"

[dev-dependencies]
fantoccini   = { version = "0.21" }
serde_json   = { version = "1.0" }
tokio-stream = { workspace = true, features = ["net"] }
tonic-web    = { version = "0.12" }
