// Required by code generated by the upstream `#[instrument]` macro.
extern crate miden_node_tracing as tracing;

mod server;
#[cfg(test)]
mod tests;

pub use server::{
    AccountAdmission,
    PreAuthSubmission,
    Rpc,
    RpcMode,
    SequencerInternal,
    ValidatorClients,
};

// CONSTANTS
// =================================================================================================
pub const COMPONENT: &str = "miden-rpc";
pub const LOG_TARGET: &str = "user::miden-rpc";
