[package]
authors.workspace      = true
description            = "Miden node binary"
edition.workspace      = true
homepage.workspace     = true
keywords               = ["miden", "node"]
license.workspace      = true
name                   = "miden-node"
readme.workspace       = true
repository.workspace   = true
rust-version.workspace = true
version.workspace      = true

[lints]
workspace = true

[features]
tracing-forest = ["miden-node-block-producer/tracing-forest"]

[dependencies]
anyhow                    = { workspace = true }
clap                      = { version = "4.5", features = ["derive", "env", "string"] }
miden-lib                 = { workspace = true }
miden-node-block-producer = { workspace = true }
miden-node-rpc            = { workspace = true }
miden-node-store          = { workspace = true }
miden-node-utils          = { workspace = true }
miden-objects             = { workspace = true }
rand                      = { workspace = true }
rand_chacha               = { version = "0.9" }
tokio                     = { workspace = true, features = ["macros", "net", "rt-multi-thread"] }
url                       = { workspace = true }

[dev-dependencies]
figment          = { version = "0.10", features = ["env", "test", "toml"] }
miden-node-utils = { workspace = true, features = ["tracing-forest"] }

[build-dependencies]
# Required to inject build metadata.
miden-node-utils = { workspace = true, features = ["vergen"] }
