[package]
authors.workspace      = true
description            = "Miden node's shared utilities"
edition.workspace      = true
homepage.workspace     = true
keywords               = ["miden", "node", "utils"]
license.workspace      = true
name                   = "miden-node-utils"
readme                 = "README.md"
repository.workspace   = true
rust-version.workspace = true
version.workspace      = true

[lints]
workspace = true

[lib]
doctest = false

[features]
rocksdb = ["dep:miden-crypto", "miden-crypto/rocksdb"]
# Enables test-only utilities.
testing        = ["miden-protocol/testing"]
testing-prover = ["dep:miden-processor", "dep:miden-testing", "dep:miden-tx", "testing"]

[dependencies]
anyhow             = { workspace = true }
backon             = { workspace = true }
clap               = { workspace = true }
fs-err             = { workspace = true }
http               = { workspace = true }
humantime          = { workspace = true }
itertools          = { workspace = true }
lru                = { workspace = true }
miden-node-tracing = { workspace = true }
miden-processor    = { optional = true, version = "0.32" }
miden-protocol     = { workspace = true }
miden-testing      = { optional = true, workspace = true }
miden-tx           = { optional = true, workspace = true }
reqwest            = { workspace = true }
thiserror          = { workspace = true }
tokio              = { features = ["macros", "rt", "signal", "time"], workspace = true }
tokio-util         = { workspace = true }
tonic              = { default-features = true, workspace = true }
tower              = { workspace = true }
tower-http         = { workspace = true }
tower_governor     = { workspace = true }
url                = { workspace = true }

# RocksDbConfig is needed due to orphan rules
miden-crypto = { optional = true, workspace = true }
