[package]
authors.workspace      = true
description            = "Miden node message definitions (Store, Block Producer and RPC)"
edition.workspace      = true
homepage.workspace     = true
keywords               = ["miden", "node", "protobuf", "rpc"]
license.workspace      = true
name                   = "miden-node-proto"
readme                 = "README.md"
repository.workspace   = true
rust-version.workspace = true
version.workspace      = true

[lints]
workspace = true

[dependencies]
anyhow                      = { workspace = true }
hex                         = { workspace = true }
http                        = { workspace = true }
miden-node-grpc-error-macro = { workspace = true }
miden-node-tracing          = { workspace = true }
miden-node-utils            = { workspace = true }
miden-objects               = { workspace = true }
miden-protocol              = { workspace = true }
prost                       = { workspace = true }
rand                        = { workspace = true }
thiserror                   = { workspace = true }
tokio                       = { features = ["macros", "rt", "time"], workspace = true }
tonic                       = { default-features = true, workspace = true }
tonic-prost                 = { workspace = true }
tower                       = { workspace = true }
url                         = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
miden-protocol = { features = ["testing"], workspace = true }

[build-dependencies]
build-rs               = { workspace = true }
codegen                = { workspace = true }
fs-err                 = { workspace = true }
miden-node-proto-build = { features = ["internal"], workspace = true }
miden-objects          = { workspace = true }
miette                 = { workspace = true }
prost-types            = { workspace = true }
tonic-prost-build      = { workspace = true }

[package.metadata.cargo-machete]
ignored = [
  "tonic-prost", # used in generated OUT_DIR code
  "tower",       # used in generated OUT_DIR code
]

[package.metadata.cargo-shear]
ignored = [
  "tower", # used in generated OUT_DIR code
]
