#!/bin/bash
#
# This is a postinstallation script so the service can be configured and started when requested.

# user is expected by the systemd service file and `/opt/<user>` is its working directory, 
sudo adduser --disabled-password --disabled-login --shell /usr/sbin/nologin --quiet --system --no-create-home --home /nonexistent miden-node

# Working folder.
if [ -d "/opt/miden-node" ]
then
    echo "Directory /opt/miden-node exists."
else
    mkdir -p /opt/miden-node
    sudo chown -R miden-node /opt/miden-node
fi

# Configuration folder
if [ -d "/etc/opt/miden-node" ]
then
    echo "Directory /etc/opt/miden-node exists."
else
    mkdir -p /etc/opt/miden-node
    sudo chown -R miden-node /etc/opt/miden-node
fi

sudo systemctl daemon-reload
