#!/bin/bash
#
###############
# Remove miden installs
##############
sudo rm -rf /lib/systemd/system/miden-node.service
sudo rm -rf /etc/miden
sudo rm -rf /opt/miden/miden-node
sudo deluser miden
sudo systemctl daemon-reload
