#!/bin/bash
#
# This is a postinstallation script so the service can be configured and started when requested.

# user is expected by the systemd service file and `/opt/<user>` is its working directory, 
sudo adduser --disabled-password --disabled-login --shell /usr/sbin/nologin --quiet --system --no-create-home --home /nonexistent miden-faucet

# Working folder.
if [ -d "/opt/miden-faucet" ]
then
    echo "Directory /opt/miden-faucet exists."
else
    mkdir -p /opt/miden-faucet
    sudo chown -R miden-faucet /opt/miden-faucet
fi

# Configuration folder
if [ -d "/etc/opt/miden-faucet" ]
then
    echo "Directory /etc/opt/miden-faucet exists."
else
    mkdir -p /etc/opt/miden-faucet
    sudo chown -R miden-faucet /etc/opt/miden-faucet
fi

sudo systemctl daemon-reload
