#!/bin/bash
#
###############
# Remove miden-funding-service install
##############
svc=miden-funding-service

sudo rm -rf "/lib/systemd/system/$svc.service"
sudo rm -rf "/etc/opt/$svc"
sudo deluser "$svc"

sudo systemctl daemon-reload
