#!/bin/bash
#
# This is a postinstallation script so the service can be configured and started when requested.

svc=miden-funding-service

# user is expected by the systemd service file and `/opt/<user>` is its working directory,
sudo adduser --disabled-password --disabled-login --shell /usr/sbin/nologin --quiet --system --no-create-home --home /nonexistent "$svc"

# Working folder.
if [ -d "/opt/$svc" ]
then
    echo "Directory /opt/$svc exists."
else
    mkdir -p "/opt/$svc"
fi
sudo chown -R "$svc" "/opt/$svc"

# Configuration folder
if [ -d "/etc/opt/$svc" ]
then
    echo "Directory /etc/opt/$svc exists."
else
    mkdir -p "/etc/opt/$svc"
fi
sudo chown -R "$svc" "/etc/opt/$svc"

sudo systemctl daemon-reload
