# Release debian packages for miden node and faucet.
name: Release packages
run-name: Release packaging for ${{ inputs.version || github.ref }}

env:
  version: ${{ inputs.version || github.ref_name }}

on:
  release:
    types: [released, prereleased]

  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag'
        required: true
        type: string

permissions:
  id-token: write
  contents: write

jobs:
  package:
    name: ${{ inputs.version }} for ${{ matrix.arch }}
    strategy:
      matrix:
        arch: [amd64, arm64]
    runs-on:
      labels: ${{ matrix.arch == 'arm64' && 'ubuntu22-arm-4core' || 'ubuntu-latest' }}
    steps:
      # Note that this checkout is _not_ used as the source for the package.
      # Instead this is required to access the workflow actions. Package source
      # selection is handled by the packaging action.
      - name: Checkout repo
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Build packages
        uses: ./.github/actions/build_package
        with:
          gitref: ${{ env.version }}

      - name: Package names
        run: |
          echo "node-package=miden-node-${{ env.version }}-${{ matrix.arch }}.deb"     >> $GITHUB_ENV
          echo "faucet-package=miden-faucet-${{ env.version }}-${{ matrix.arch }}.deb" >> $GITHUB_ENV

      - name: Rename package files
        run: |
          mv miden-node.deb   ${{ env.node-package }}
          mv miden-faucet.deb ${{ env.faucet-package }}

      - name: shasum packages
        run: |
          sha256sum ${{ env.node-package }}   > ${{ env.node-package }}.checksum
          sha256sum ${{ env.faucet-package }} > ${{ env.faucet-package }}.checksum

      - name: Publish packages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ env.version }} \
            ${{ env.node-package }} \
            ${{ env.node-package }}.checksum \
            ${{ env.faucet-package }} \
            ${{ env.faucet-package }}.checksum \
            --clobber
