name: Publish All Debian Packages

on:
  release:
    types: [prereleased, released]

  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (E.G. v0.10.0-rc.1, v0.10.0). Corresponding git tag must already exist."
        required: true
        type: string

env:
  version: ${{ inputs.version || github.ref_name }}

permissions:
  contents: read

jobs:
  publish:
    name: Publish ${{ matrix.component.name }} ${{ matrix.arch }} Debian
    permissions:
      contents: write
    strategy:
      matrix:
        arch: [amd64, arm64]
        component:
          - name: node
            extra_deps: true
          - name: prover
            crate_dir: remote-prover
            crate: miden-remote-prover
            extra_deps: false
          - name: validator
            extra_deps: true
          - name: ntx-builder
            extra_deps: true
          - name: network-monitor
            extra_deps: false
          - name: funding-service
            extra_deps: false
    runs-on:
      labels: ${{ matrix.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - if: ${{ matrix.component.extra_deps }}
        uses: ./.github/actions/install-rocksdb
      - if: ${{ matrix.component.extra_deps }}
        uses: ./.github/actions/install-protobuf-compiler
      - name: Build and Publish ${{ matrix.component.name }}
        uses: ./.github/actions/debian
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gitref: ${{ env.version }}
          crate_dir: ${{ matrix.component.crate_dir || matrix.component.name }}
          package: miden-${{ matrix.component.name }}
          packaging_dir: ${{ matrix.component.name }}
          crate: ${{ matrix.component.crate || format('miden-{0}', matrix.component.name) }}
          arch: ${{ matrix.arch }}
